-- People often copy jobs. When they do, the GM table does not exist anymore.
-- This line makes the job code work both inside and outside of gamemode files.
-- You should not copy this line into your code.
local GAMEMODE = GAMEMODE or GM
/*--------------------------------------------------------
Default teams. Please do not edit this file. Please use the darkrpmod addon instead.
--------------------------------------------------------*/
TEAM_CITIZEN = DarkRP.createJob("Civilian", {
	color = Color(20, 150, 20, 255),
	model = {
		"models/player/Group03/Female_01.mdl",
		"models/player/Group03/Female_02.mdl",
		"models/player/Group03/Female_03.mdl",
		"models/player/Group03/Female_04.mdl",
		"models/player/Group03/Female_06.mdl",
		"models/player/group03/male_01.mdl",
		"models/player/Group03/Male_02.mdl",
		"models/player/Group03/male_03.mdl",
		"models/player/Group03/Male_04.mdl",
		"models/player/Group03/Male_05.mdl",
		"models/player/Group03/Male_06.mdl",
		"models/player/Group03/Male_07.mdl",
		"models/player/Group03/Male_08.mdl",
		"models/player/Group03/Male_09.mdl"}
	},
	description = [[The Citizen is the most basic level of society you can hold besides being a hobo. You have no specific role in city life.]],
	weapons = {},
	command = "civilian",
	max = 0,
	salary = GAMEMODE.Config.normalsalary,
	admin = 0,
	vote = false,
	hasLicense = false,
	candemote = false,
	category = "Citizens",
})

TEAM_SCAVENGER = AddExtraTeam("Scavenger", {
	level = 1,
    color = Color(100, 100, 100, 255),
    model = "models/player/arctic.mdl",
    description = [[Go out and scavenge through the Cilians bases and take their stuff.]],
    weapons = {"weapon_fists", "lockpick", "keypad_cracker"},
    command = "scavenger",
    max = 10,
    salary = 45,
    admin = 0,
    vote = false,
    hasLicense = false,
    ammo = {
        ["pistol"] = 60,
    },
})

TEAM_GUN = AddExtraTeam("Weapons Dealer", {
    level = 1,
    color = Color(100, 100, 100, 255),
    model = "models/player/pmc_3/pmc__01.mdl",
    description = [[Neautral party to all wars. Supply weapons to soldiers.]],
    weapons = {},
    command = "dealer",
    max = 5,
    salary = 45,
    admin = 0,
    vote = false,
    hasLicense = false,
})

TEAM_USMC1 = AddExtraTeam("US Private", {
	level = 1,
    color = Color(0, 150, 255, 255),
    model = "models/player/rusty/natguard/male_07.mdl",
    description = [[US Private]], 
    weapons = {"bb_glock_alt", ,
    command = "usmc1",
    max = 10,
    salary = 45,
    admin = 0,
    vote = false,
    hasLicense = false,
    ammo = {
        ["pistol"] = 60,
    },
})

TEAM_USMC2 = AddExtraTeam("US P.F.C", {
	level = 5,
    color = Color(0, 150, 255, 255),
    model = "models/player/rusty/natguard/male_07.mdl",
    description = [[US P.F.C]],
    weapons = {"bb_glock_alt",  "bb_tmp_alt"},
    command = "usmc2",
	max = 5,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_USMC1,
    ammo = {
        ["pistol"] = 60,
		["smg1"] = 60,
    },
})

TEAM_USMC3 = AddExtraTeam("US Corporal", {
	level = 10,
    color = Color(0, 150, 255, 255),
    model = "models/codmw2/codmw2h.mdl",
    description = [[US Corporal]],
    weapons = {"bb_glock_alt",  "bb_ump45_alt"},
    command = "usmc3",
    max = 10,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_USMC2,
    ammo = {
        ["pistol"] = 60,
		["smg1"] = 160,
    },
})

TEAM_USMC4 = AddExtraTeam("US Sergeant", {
	level = 20,
    color = Color(0, 150, 255, 255),
    model = "models/codmw2/codmw2.mdl",
    description = [[US Sergeant]],
    weapons = {"bb_fiveseven_alt",  "bb_m3_alt"},
    command = "usmc4",
    max = 10,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_USMC3,
    ammo = {
        ["357"] = 60,
		["buckshot"] = 160,
    },
})

TEAM_USMC5 = AddExtraTeam("US Master Sergeant", {
	level = 25,
    color = Color(0, 150, 255, 255),
    model = "models/codmw2/codmw2.mdl",
    description = [[ US Master Sergeant]],
    weapons = {"bb_mp5_alt",  "bb_scout_alt", "bb_fiveseven_alt"},
    command = "usmc5",
    max = 10,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_USMC4,
    ammo = {
        ["pistol"] = 60,
		["smg1"] = 160,
    },
})

TEAM_USMC6 = AddExtraTeam("US Lieutenant", {
	level = 30,
    color = Color(0, 150, 255, 255),
    model = "models/codmw2/codmw2h.mdl",
    description = [[ US Lieutenant]],
    weapons = { "bb_famas_alt", "bb_usp_alt"},
    command = "usmc6",
    max = 10,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_USMC5,
    ammo = {
                ["pistol"] = 60,
				["smg1"] = 160,
    },
})

TEAM_USMC7 = AddExtraTeam("US Captain", {
	level = 40,
    color = Color(0, 150, 255, 255),
    model = "models/codmw2/t_codmw2.mdl",
    description = [[US Captain.]],
    weapons = { "bb_famas_alt", "bb_usp_alt", "bb_cssfrag_alt"},
    command = "usmc7",
    max = 10,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_USMC6,
    ammo = {
        ["357"] = 60,
		["smg1"] = 160,
    },
})

TEAM_USMC8 = AddExtraTeam("US Colonel", {
	level = 50,
    color = Color(0, 150, 255, 255),
    model = "models/codmw2/codmw2he.mdl",
    description = [[US Colonial.]],
    weapons = {"med_kit", "bb_m3_alt",  "bb_m4a1_alt", "bb_deagle_alt", "bb_cssfrag_alt"},
    command = "usmc8",
    max = 10,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_USMC7,
    ammo = {
        ["357"] = 60,
		["ar2"] = 160,
		["buckshot"] = 160,
    },
})

TEAM_USMC9 = AddExtraTeam("US Brigadier", {
	level = 65,
    color = Color(0, 150, 255, 255),
    model = "models/player/pmc_2/pmc__03.mdl",
    description = [[US Brigadier.]],
    weapons = {"med_kit",  "bb_scout_alt", "bb_tmp_alt", "bb_cssfrag_alt"},
    command = "usmc9",
    max = 5,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_USMC8,
    ammo = {
        ["357"] = 60,
		["ar2"] = 160,
		["buckshot"] = 160,
    },
})

TEAM_USMC10 = AddExtraTeam("US General", {
	level = 80,
    color = Color(0, 150, 255, 255),
    model = "models/player/pmc_2/pmc__02.mdl",
    description = [[US General.]],
    weapons = {"med_kit", "bb_m3_alt",  "bb_m4a1_alt", "weapon_doorbuster", "bb_cssfrag_alt"},
    command = "usmc10",
    max = 5,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_USMC9,
    ammo = {
        ["357"] = 60,
		["ar2"] = 160,
		["buckshot"] = 160,
    },
})

TEAM_USMC11 = AddExtraTeam("US Major General", {
	level = 95,
    color = Color(0, 150, 255, 255),
    model = "models/player/pmc_2/pmc__04.mdl",
    description = [[US Major General.]],
    weapons = {"med_kit",  "bb_m4a1_alt", "bb_deagle_alt", "bb_cssfrag_alt"},
    command = "usmc11",
    max = 2,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_USMC9,
    ammo = {
        ["pistol"] = 60,
		["ar2"] = 160,
		["buckshot"] = 160,
    },
})

TEAM_USMC12 = AddExtraTeam("US General of the Army", {
	level = 95,
    color = Color(0, 150, 255, 255),
    model = "models/player/pmc_2/pmc__04.mdl",
    description = [[US General of the army.]],
    weapons = {"med_kit",  "bb_m4a1_alt", "bb_deagle_alt", "bb_cssfrag_alt"},
    command = "usmc12",
    max = 1,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_USMC9,
    ammo = {
        ["pistol"] = 60,
		["ar2"] = 160,
		["buckshot"] = 160,
    },
})

TEAM_USMC13 = AddExtraTeam("US Recon Sniper", {
    level = 50,
    color = Color(0, 150, 255, 255),
    model = "models/player/ghillieplayer.mdl",
    description = [[US recon sniper.]],
    weapons = {"med_kit",  "m9k_m98b", "m9k_mp5sd",},
    command = "usmc13",
    max = 5,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
    NeedToChangeFrom = TEAM_USMC7,
    ammo = {
        ["pistol"] = 60,
        ["SniperPenetratedRound"] = 160,
    },
})

TEAM_CUBAN1 = AddExtraTeam("Cuban Private", {
	level = 1,
    color = Color(150, 150, 0, 255),
    model = "models/cod players/opfor1.mdl",
    description = [[Cuban Private]],
    weapons = {"bb_glock_alt", ,
    command = "cuban1",
    max = 10,
    salary = 45,
    admin = 0,
    vote = false,
    hasLicense = false,
    ammo = {
        ["pistol"] = 60,
    },
})

TEAM_CUBAN2 = AddExtraTeam("Cuban P.F.C", {
		level = 5,
        color = Color(150, 150, 0, 255),
        model = "models/cod players/opfor1.mdl",
        description = [[ Cuban P.F.C]],
        weapons = {"bb_glock_alt",  "bb_mac10_alt"},
        command = "cuban2",
        max = 10,
        salary = 55,
        admin = 0,
        vote = false,
        hasLicense = false,
		NeedToChangeFrom = TEAM_CUBAN1,
        ammo = {
                ["pistol"] = 60,
				["smg1"] = 60,
        },
})

TEAM_CUBAN3 = AddExtraTeam("Cuban Corporal", {
		level = 10,
        color = Color(150, 150, 0, 255),
        model = "models/cod players/opfor5.mdl",
        description = [[ Cuban Corporal]],
        weapons = {"bb_glock_alt",  "bb_mac10_alt"},
        command = "cuban3",
        max = 10,
        salary = 55,
        admin = 0,
        vote = false,
        hasLicense = false,
		NeedToChangeFrom = TEAM_CUBAN2,
        ammo = {
                ["pistol"] = 60,
				["smg1"] = 160,
        },
})

TEAM_CUBAN4 = AddExtraTeam("Cuban Sergeant", {
		level = 20,
        color = Color(150, 150, 0, 255),
        model = "models/cod players/opfor1.mdl",
        description = [[ cuban Sergeant ]],
        weapons = {"bb_usp_alt",  "bb_m3_alt"},
        command = "cuban4",
        max = 10,
        salary = 55,
        admin = 0,
        vote = false,
        hasLicense = false,
		NeedToChangeFrom = TEAM_CUBAN3,
        ammo = {
                ["357"] = 60,
				["buckshot"] = 160,
        },
})

TEAM_CUBAN5 = AddExtraTeam("Cuban Master Sergeant", {
		level = 25,
        color = Color(150, 150, 0, 255),
        model = "models/cod players/opfor4.mdl",
        description = [[Cuban Master Sergeant]],
        weapons = {"bb_tmp_alt",  "bb_scout_alt", "bb_usp_alt"},
        command = "cuban5",
        max = 10,
        salary = 55,
        admin = 0,
        vote = false,
        hasLicense = false,
		NeedToChangeFrom = TEAM_CUBAN4,
        ammo = {
                ["pistol"] = 60,
				["smg1"] = 160,
        },
})

TEAM_CUBAN6 = DarkRP.createJob("Cuban Lieutenant", {
		level = 30,
        color = Color(150, 150, 0, 255),
        model = "models/cod players/opfor1.mdl",
        description = [[Cuban Lieutenant]],
        weapons = { "bb_sg552_alt", "bb_p228_alt"},
        command = "cuban6",
        max = 10,
        salary = 55,
        admin = 0,
        vote = false,
        hasLicense = false,
		NeedToChangeFrom = TEAM_CUBAN5,
        ammo = {
                ["pistol"] = 60,
				["smg1"] = 160,
        },
})

TEAM_CUBAN7 = DarkRP.createJob("Cuban Captain", {
		level = 40,
        color = Color(150, 150, 0, 255),
        model = "models/cod players/opfor2.mdl",
        description = [[Cuban Captain]],
        weapons = { "bb_sg552_alt", "bb_p228_alt", "bb_cssfrag_alt"},
        command = "cuban7",
        max = 10,
        salary = 55,
        admin = 0,
        vote = false,
        hasLicense = false,
		NeedToChangeFrom = TEAM_CUBAN6,
        ammo = {
                ["357"] = 60,
				["ar2"] = 160,
        },
})

TEAM_CUBAN8 = DarkRP.createJob("Cuban Colonel", {
	level = 50,
    color = Color(150, 150, 0, 255),
    model = "models/cod players/opfor3.mdl",
    description = [[Cuban Colonel]],
    weapons = {"med_kit",  "bb_ump45_alt", "bb_deagle_alt", "bb_cssfrag_alt", "bb_m3_alt"},
    command = "cuban8",
    max = 10,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_CUBAN7,
    ammo = {
        ["357"] = 60,
		["ar2"] = 160,
		["buckshot"] = 60,
    },
})

TEAM_CUBAN9 = AddExtraTeam("Cuban Brigadier", {
	level = 65,
    color = Color(150, 150, 0, 255),
    model = "models/cod players/opfor1.mdl",
    description = [[Cuban Brigadier]],
    weapons = {"med_kit",  "bb_ump45_alt", "bb_mac10_alt", "bb_cssfrag_alt"},
    command = "cuban9",
    max = 5,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_CUBAN8,
    ammo = {
        ["357"] = 60,
		["ar2"] = 160,
		["buckshot"] = 160,
    },
})

TEAM_CUBAN10 = AddExtraTeam("Cuban General", {
	level = 80,
    color = Color(150, 150, 0, 255),
    model = "models/cod players/opfor4.mdl",
    description = [[Cuban General]],
    weapons = {"med_kit", "bb_m3_alt",  "bb_p90_alt", "weapon_doorbuster", "bb_cssfrag_alt"},
    command = "cuban10",
    max = 5,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_CUBAN9,
    ammo = {
        ["357"] = 60,
		["ar2"] = 160,
		["buckshot"] = 160,
    },
})

TEAM_CUBAN11 = AddExtraTeam("Cuban Major General", {
	level = 95,
    color = Color(150, 150, 0, 255),
    model = "models/cod players/opfor5.mdl",
    description = [[Cuban Major General.]],
    weapons = {"med_kit",  "bb_sg552_alt", "bb_deagle_alt", "bb_cssfrag_alt"},
    command = "cuban11",
    max = 2,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_CUBAN9,
    ammo = {
        ["pistol"] = 60,
		["ar2"] = 160,
		["buckshot"] = 160,
    },
})

TEAM_CUBAN12 = AddExtraTeam("Cuban General of the Army", {
	level = 100,
    color = Color(150, 150, 0, 255),
    model = "models/cod players/opfor5.mdl",
    description = [[Cuban Major General.]],
    weapons = {"med_kit",  "bb_sg552_alt", "bb_p90_alt", "bb_cssfrag_alt"},
    command = "cuban12",
    max = 1,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_CUBAN9,
    ammo = {
        ["pistol"] = 60,
		["ar2"] = 160,
		["buckshot"] = 160,
    },
})

TEAM_CUBAN13 = AddExtraTeam("Cuban Recon Sniper", {
    level = 50,
    color = Color(150, 150, 0, 255),
    model = "models/player/ghillieplayer.mdl",
    description = [[Cuban recon sniper.]],
    weapons = {"med_kit",  "m9k_m24", "m9k_mp5sd",},
    command = "cuban13",
    max = 5,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
    NeedToChangeFrom = TEAM_CUBAN7,
    ammo = {
        ["pistol"] = 60,
        ["SniperPenetratedRound"] = 160,
    },
})

TEAM_RUSSIAN1 = DarkRP.createJob("Russian Private", {
		level = 1,
        color = Color(255, 0, 0, 255),
        model = "models/mw2guy/rus/soldier_a.mdl",
        description = [[Russian Private]],
        weapons = {"bb_p228_alt", ,
        command = "russian1",
        max = 10,
        salary = 45,
        admin = 0,
        vote = false,
        hasLicense = false,
        ammo = {
                ["pistol"] = 60,
        },
})

TEAM_RUSSIAN2 = DarkRP.createJob("Russian P.F.C", {
		level = 5,
        color = Color(255, 0, 0, 255),
        model = "models/mw2guy/rus/soldier_a.mdl",
        description = [[Russian P.F.C]],
        weapons = {"bb_p228_alt",  "bb_tmp_alt"},
        command = "russian2",
        max = 10,
        salary = 55,
        admin = 0,
        vote = false,
        hasLicense = false,
		NeedToChangeFrom = TEAM_RUSSIAN1,
        ammo = {
                ["pistol"] = 60,
				["smg1"] = 60,
        },
})


TEAM_RUSSIAN3 = DarkRP.createJob("Russian Corporal", {
		level = 10,
        color = Color(255, 0, 0, 255),
        model = "models/mw2guy/rus/soldier_f.mdl",
        description = [[Russian Corporal]],
        weapons = {"bb_p228_alt",  "bb_ump45_alt"},
        command = "russian3",
        max = 10,
        salary = 55,
        admin = 0,
        vote = false,
        hasLicense = false,
		NeedToChangeFrom = TEAM_RUSSIAN2,
        ammo = {
                ["pistol"] = 60,
				["smg1"] = 160,
        },
})

TEAM_RUSSIAN4 = DarkRP.createJob("Russian Sergeant", {
		level = 20,
        color = Color(255, 0, 0, 255),
        model = "models/mw2guy/riot/riot_ru.mdl",
        description = [[Russian Sergeant]],
        weapons = {"bb_p228_alt",  "bb_m3_alt"},
        command = "russian4",
        max = 10,
        salary = 55,
        admin = 0,
        vote = false,
        hasLicense = false,
		NeedToChangeFrom = TEAM_RUSSIAN3,
        ammo = {
                ["357"] = 60,
				["buckshot"] = 160,
        },
})

TEAM_RUSSIAN5 = DarkRP.createJob("Russian Master Sergeant", {
	level = 25,
    color = Color(255, 0, 0, 255),
    model = "models/mw2guy/rus/soldier_f.mdl",
    description = [[Russian Master Sergeant]],
    weapons = {"bb_fiveseven_alt",  "bb_scout_alt", "bb_tmp_alt"},
    command = "russian5",
    max = 10,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_RUSSIAN4,
    ammo = {
        ["pistol"] = 60,
		["smg1"] = 160,
    },
})

TEAM_RUSSIAN6 = DarkRP.createJob("Russian Lieutenant", {
	level = 30,
    color = Color(255, 0, 0, 255),
    model = "models/mw2guy/riot/riot_ru.mdl",
    description = [[Russian Lieutenant]],
    weapons = {"bb_deagle_alt",  "bb_galil_alt"},
    command = "russian6",
    max = 10,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_RUSSIAN5,
    ammo = {
        ["357"] = 30,
		["smg1"] = 160,
    },
})

TEAM_RUSSIAN7 = DarkRP.createJob("Russian Captain", {
	level = 40,
    color = Color(255, 0, 0, 255),
    model = "models/mw2guy/rus/soldier_f.mdl",
    description = [[Russian Captain]],
    weapons = {"bb_deagle_alt",  "bb_ak47_alt"},
    command = "russian7",
    max = 10,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_RUSSIAN6,
    ammo = {
		["ar2"] = 160,
		["357"] = 30,
    },
})

TEAM_RUSSIAN8 = DarkRP.createJob("Russian Colonel", {
	level = 50,
    color = Color(255, 0, 0, 255),
    model = "models/mw2guy/rus/gassoldier.mdl",
    description = [[Russian Colonel]],
    weapons = {"med_kit", "bb_deagle_alt",  "bb_ak47_alt", "bb_cssfrag_alt"},
    command = "russian8",
    max = 10,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_RUSSIAN7,
    ammo = {
		["ar2"] = 160,
		["357"] = 30,
		["buckshot"] = 60,
    },
})

TEAM_RUSSIAN9 = AddExtraTeam("Russian Brigadier", {
	level = 65,
    color = Color(255, 0, 0, 255),
    model = "models/mw2guy/rus/gassoldier.mdl",
    description = [[Russian Brigadier]],
    weapons = {"med_kit",  "bb_ak47_alt", "bb_mac10_alt", "bb_cssfrag_alt"},
    command = "russian9",
    max = 5,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_RUSSIAN8,
    ammo = {
        ["357"] = 60,
		["ar2"] = 160,
		["buckshot"] = 160,
    },
})

TEAM_RUSSIAN10 = AddExtraTeam("Russian General", {
	level = 80,
    color = Color(255, 0, 0, 255),
    model = "models/mw2guy/rus/soldier_c.mdl",
    description = [[Russian General]],
    weapons = {"med_kit", "bb_m3_alt",  "bb_galil_alt", "weapon_doorbuster", "bb_cssfrag_alt"},
    command = "russian10",
    max = 1,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_RUSSIAN9,
    ammo = {
        ["357"] = 60,
		["ar2"] = 160,
		["buckshot"] = 160,
    },
})

TEAM_RUSSIAN11 = AddExtraTeam("Russian Major General", {
	level = 95,
    color = Color(255, 0, 0, 255),
    model = "models/mw2guy/rus/soldier_f.mdl",
    description = [[Russian Major General]],
    weapons = {"med_kit",  "bb_galil_alt", "m9k_deagle", "bb_cssfrag_alt"},
    command = "russian11",
    max = 1,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_RUSSIAN9,
    ammo = {
        ["pistol"] = 60,
		["ar2"] = 160,
		["buckshot"] = 160,
    },
})

TEAM_RUSSIAN12 = AddExtraTeam("Russian General of the Army", {
	level = 100,
    color = Color(255, 0, 0, 255),
    model = "models/mw2guy/rus/soldier_f.mdl",
    description = [[Russian General of the army.]],
    weapons = {"med_kit",  "bb_ak47_alt", "bb_deagle_alt", "bb_cssfrag_alt"},
    command = "russian12",
    max = 1,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_RUSSIAN9,
    ammo = {
        ["pistol"] = 60,
		["ar2"] = 160,
		["buckshot"] = 160,
    },
})

TEAM_RUSSIAN13 = AddExtraTeam("Russian Recon Sniper", {
    level = 50,
    color = Color(255, 0, 0, 255),
    model = "models/player/ghillieplayer.mdl",
    description = [[Russian recon sniper.]],
    weapons = {"med_kit",  "m9k_svt40", "m9k_mp5sd",},
    command = "russian13",
    max = 5,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
    NeedToChangeFrom = TEAM_RUSSIAN7,
    ammo = {
        ["pistol"] = 60,
        ["SniperPenetratedRound"] = 160,
    },
})

TEAM_GERMAN1 = AddExtraTeam("German Private", {
	level = 5,
    color = Color(0, 255, 155, 255),
    model = "models/player/pmc_4/pmc__11.mdl",
    description = [[Lowest level of the German Army.]],
    weapons = {"bb_glock_alt", ,
    command = "german1",
    max = 10,
    salary = 45,
    admin = 0,
    vote = false,
    hasLicense = false,
    ammo = {
        ["pistol"] = 60,
    },
})

TEAM_GERMAN2 = AddExtraTeam("German P.F.C", {
	level = 10,
    color = Color(0, 255, 155, 255),
    model = "models/player/pmc_4/pmc__09.mdl",
    description = [[Second lowest level of the German Army.]],
    weapons = {"bb_usp_alt",  "bb_p90_alt"},
    command = "german2",
	max = 10,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_GERMAN1, 
    ammo = {
        ["pistol"] = 60,
		["smg1"] = 60,
    },
})

TEAM_GERMAN3 = AddExtraTeam("German Corporal", {
	level = 15,
    color = Color(0, 255, 155, 255),
    model = "models/player/pmc_4/pmc__06.mdl",
    description = [[German Corporal]],
    weapons = {"bb_usp_alt",  "bb_mp5_alt"},
    command = "german3",
    max = 10,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_GERMAN2,
    ammo = {
        ["pistol"] = 60,
		["smg1"] = 160,
    },
})

TEAM_GERMAN4 = AddExtraTeam("German Sergeant", {
	level = 20,
    color = Color(0, 255, 155, 255),
    model = "models/player/pmc_4/pmc__14.mdl",
    description = [[German Sergeant]],
    weapons = {"bb_glock_alt",  "bb_p90_alt"},
    command = "german4",
    max = 10,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_GERMAN3,
    ammo = {
        ["357"] = 60,
		["buckshot"] = 160,
    },
})

TEAM_GERMAN5 = AddExtraTeam("German Master Sergeant", {
	level = 40,
    color = Color(0, 255, 155, 255),
    model = "models/player/pmc_1/pmc__03.mdl",
    description = [[German Master Sergeant]],
    weapons = {"bb_tmp_alt",  "bb_scout_alt", "bb_fiveseven_alt"},
    command = "german5",
    max = 10,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_GERMAN4,
    ammo = {
        ["pistol"] = 120,
		["ar2"] = 160,
    },
})

TEAM_GERMAN6 = AddExtraTeam("German Lieutenant", {
	level = 60,
    color = Color(0, 255, 155, 255),
    model = "models/player/pmc_1/pmc__07.mdl",
    description = [[German Lieutenant]],
    weapons = { "bb_famas_alt", "bb_fiveseven_alt"},
    command = "german6",
    max = 10,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_GERMAN5,
    ammo = {
                ["pistol"] = 60,
				["ar2"] = 160,
    },
})

TEAM_GERMAN7 = AddExtraTeam("German Captain", {
	level = 80,
    color = Color(0, 255, 155, 255),
    model = "models/player/pmc_1/pmc__07.mdl",
    description = [[German Captain]],
    weapons = { "bb_galil_alt", "bb_p228_alt", "bb_cssfrag_alt"},
    command = "german7",
    max = 10,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_GERMAN6,
    ammo = {
        ["357"] = 60,
		["ar2"] = 160,
    },
})

TEAM_GERMAN8 = AddExtraTeam("German Colonel", {
	level = 100,
    color = Color(0, 255, 155, 255),
    model = "models/player/pmc_1/pmc__04.mdl",
    description = [[German Colonel]],
    weapons = {"bb_awp_alt",  "bb_galil_alt", "bb_p228_alt", "bb_cssfrag_alt", "med_kit" },
    command = "german8",
    max = 10,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_GERMAN7,
    ammo = {
        ["357"] = 60,
		["ar2"] = 300,
		["buckshot"] = 160,
    },
})

TEAM_GERMAN9 = AddExtraTeam("German Brigadier", {
	level = 100,
    color = Color(0, 255, 155, 255),
    model = "models/player/pmc_1/pmc__04.mdl",
    description = [[German Colonel]],
    weapons = {"bb_awp_alt",  "bb_galil_alt", "bb_p228_alt", "bb_cssfrag_alt", "med_kit" },
    command = "german9",
    max = 1,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_GERMAN8,
    ammo = {
        ["357"] = 60,
		["ar2"] = 300,
		["buckshot"] = 160,
    },
})

TEAM_GERMAN10 = AddExtraTeam("German General", {
	level = 100,
    color = Color(0, 255, 155, 255),
    model = "models/player/pmc_1/pmc__04.mdl",
    description = [[German Colonel]],
    weapons = { "bb_galil_alt", "bb_p228_alt", "bb_cssfrag_alt", "med_kit" },
    command = "german10",
    max = 1,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_GERMAN9,
    ammo = {
        ["357"] = 60,
		["ar2"] = 300,
		["buckshot"] = 160,
    },
})

TEAM_GERMAN11 = AddExtraTeam("German Major General", {
	level = 100,
    color = Color(0, 255, 155, 255),
    model = "models/player/pmc_1/pmc__04.mdl",
    description = [[German Colonel]],
    weapons = { "bb_galil_alt", "bb_p228_alt", "bb_cssfrag_alt", "med_kit" },
    command = "german11",
    max = 1,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_GERMAN9,
    ammo = {
        ["357"] = 60,
		["ar2"] = 300,
		["buckshot"] = 160,
    },
})

TEAM_GERMAN12 = AddExtraTeam("German General of the Army", {
	level = 100,
    color = Color(0, 255, 155, 255),
    model = "models/player/pmc_1/pmc__04.mdl",
    description = [[German General of the Army]],
    weapons = { "bb_galil_alt", "bb_p228_alt", "bb_cssfrag_alt", "med_kit" },
    command = "german12",
    max = 1,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
	NeedToChangeFrom = TEAM_GERMAN9,
    ammo = {
        ["357"] = 60,
		["ar2"] = 300,
		["buckshot"] = 160,
    },
})

TEAM_GERMAN13 = AddExtraTeam("German Recon Sniper", {
    level = 50,
    color = Color(0, 255, 155, 255),
    model = "models/player/ghillieplayer.mdl",
    description = [[German recon sniper.]],
    weapons = {"med_kit", "m9k_intervention", "mrp_mp5"},
    command = "german13",
    max = 5,
    salary = 55,
    admin = 0,
    vote = false,
    hasLicense = false,
    NeedToChangeFrom = TEAM_GERMAN7,
    ammo = {
        ["pistol"] = 60,
        ["SniperPenetratedRound"] = 160,
        ["smg"] = 120,
    },
})

TEAM_ADMIN = AddExtraTeam("Admin on Duty", {
    color = Color(255, 0, 0, 255),
    model = "models/player/combine_super_soldier.mdl",
    description = [[Youre an admin, help the server out as much as you can! You are outside of RP. DO NOT RP IN ANYWAY!
    Can Raid = NO
    Can Mug = NO]],
    weapons = {},
    command = "admin",
    max = 0,
    salary = 0,
    admin = 1,
    vote = false,
    hasLicense = true
})

-- Compatibility for when default teams are disabled
TEAM_CITIZEN = TEAM_CITIZEN  or -1
TEAM_POLICE  = TEAM_POLICE   or -1
TEAM_GANG    = TEAM_GANG     or -1
TEAM_MOB     = TEAM_MOB      or -1
TEAM_GUN     = TEAM_GUN      or -1
TEAM_MEDIC   = TEAM_MEDIC    or -1
TEAM_CHIEF   = TEAM_CHIEF    or -1
TEAM_MAYOR   = TEAM_MAYOR    or -1
TEAM_HOBO    = TEAM_HOBO     or -1


/*
--------------------------------------------------------
HOW TO MAKE A DOOR GROUP
--------------------------------------------------------
AddDoorGroup("NAME OF THE GROUP HERE, you see this when looking at a door", Team1, Team2, team3, team4, etc.)


The default door groups, can also be used as examples:
*/
AddDoorGroup("Cops and Mayor only", TEAM_CHIEF, TEAM_POLICE, TEAM_MAYOR)
AddDoorGroup("Gundealer only", TEAM_GUN)


/*
--------------------------------------------------------
HOW TO MAKE AN AGENDA
--------------------------------------------------------
DarkRP.createAgenda(Title of the agenda, Manager (who edits it), Listeners (the ones who just see and follow the agenda))
It's possible to have multiple managers. In that case you have to put all the managers in '{}' (see Police agenda)

The default agendas, can also be used as examples:
*/
DarkRP.createAgenda("Gangster's agenda", TEAM_MOB, {TEAM_GANG})
DarkRP.createAgenda("Police agenda", {TEAM_MAYOR, TEAM_CHIEF}, {TEAM_POLICE})


/*
---------------------------------------------------------------------------
HOW TO MAKE A GROUP CHAT
---------------------------------------------------------------------------
Pick one!
DarkRP.createGroupChat(List of team variables separated by comma)

or

DarkRP.createGroupChat(a function with ply as argument that returns whether a random player is in one chat group)
This one is for people who know how to script Lua.

*/
DarkRP.createGroupChat(function(ply) return ply:isCP() end)
DarkRP.createGroupChat(TEAM_MOB, TEAM_GANG)
DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)

/*---------------------------------------------------------------------------
Define which team joining players spawn into and what team you change to if demoted
---------------------------------------------------------------------------*/
GAMEMODE.DefaultTeam = TEAM_CITIZEN

/*---------------------------------------------------------------------------
Define which teams belong to civil protection
Civil protection can set warrants, make people wanted and do some other police related things
---------------------------------------------------------------------------*/
GAMEMODE.CivilProtection = {
	[TEAM_POLICE] = true,
	[TEAM_CHIEF] = true,
	[TEAM_MAYOR] = true,
}

/*---------------------------------------------------------------------------
Enable hitman goodies on this team
---------------------------------------------------------------------------*/
DarkRP.addHitmanTeam(TEAM_MOB)

/*---------------------------------------------------------------------------
Default demote groups
---------------------------------------------------------------------------*/
DarkRP.createDemoteGroup("Cops", {TEAM_POLICE, TEAM_CHIEF})
DarkRP.createDemoteGroup("Gangsters", {TEAM_GANG, TEAM_MOB})

/*---------------------------------------------------------------------------
Default categories
---------------------------------------------------------------------------*/
DarkRP.createCategory{
	name = "Citizens",
	categorises = "jobs",
	startExpanded = true,
	color = Color(0, 107, 0, 255),
	canSee = fp{fn.Id, true},
	sortOrder = 100,
}

DarkRP.createCategory{
	name = "Civil Protection",
	categorises = "jobs",
	startExpanded = true,
	color = Color(25, 25, 170, 255),
	canSee = fp{fn.Id, true},
	sortOrder = 101,
}

DarkRP.createCategory{
	name = "Gangsters",
	categorises = "jobs",
	startExpanded = true,
	color = Color(75, 75, 75, 255),
	canSee = fp{fn.Id, true},
	sortOrder = 101,
}

DarkRP.createCategory{
	name = "Other",
	categorises = "jobs",
	startExpanded = true,
	color = Color(0, 107, 0, 255),
	canSee = fp{fn.Id, true},
	sortOrder = 255,
}
